// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5357/' | (string & {});
};

export type TodoItem = {
    id?: number;
    title?: string | null;
    isCompleted?: boolean;
    createdAt?: string;
};

export type WeatherForecast = {
    date: string;
    temperatureC: number;
    summary: string | null;
    temperatureF?: number;
};

export type GetWeatherForecastData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/weatherforecast';
};

export type GetWeatherForecastResponses = {
    /**
     * OK
     */
    200: Array<WeatherForecast>;
};

export type GetWeatherForecastResponse = GetWeatherForecastResponses[keyof GetWeatherForecastResponses];

export type GetTodoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/Todo';
};

export type GetTodoResponses = {
    /**
     * OK
     */
    200: Array<TodoItem>;
};

export type GetTodoResponse = GetTodoResponses[keyof GetTodoResponses];

export type PostTodoData = {
    body: TodoItem;
    path?: never;
    query?: never;
    url: '/Todo';
};

export type PostTodoResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteTodoByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/Todo/{id}';
};

export type DeleteTodoByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetTodoByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/Todo/{id}';
};

export type GetTodoByIdResponses = {
    /**
     * OK
     */
    200: TodoItem;
};

export type GetTodoByIdResponse = GetTodoByIdResponses[keyof GetTodoByIdResponses];

export type PutTodoByIdData = {
    body: TodoItem;
    path: {
        id: number;
    };
    query?: never;
    url: '/Todo/{id}';
};

export type PutTodoByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};
